name: Deploy Next.js to Linux server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2243 mmontt.ddns.net >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 desarrollo@mmontt.ddns.net -p 2243 << 'EOF'
            cd /opt/cloudperformance-webpage
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          EOF
