name: Deploy Next.js to Linux server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2243 mmontt.ddns.net >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2243
          script: |
            set -ex
            cd /opt/cloudperformance-webpage
            sudo git pull origin main
            sudo npm install
            sudo rm -rfd ./.next
            sudo stdbuf -oL npm run build
            echo "Build exit status: $?"
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          EOF
